### ISSUE TITLE
Data Sync when no internet connect is available. 

### ISSUE THREAD

**Issue by kennedyopokuasare** [denzilferreira/EXTREMA#1]
In the referenced line, I believe the code is assuming that internet connection is available and data has been transferred successfully.
Assuming the data sync fails, the dataset in this process will be marked as transferred which may not be the case.

https://github.com/denzilferreira/EXTREMA/blob/39cef6cb0d8fbfb0ae6cc4077732449f8844bc39/app/src/main/java/fi/oulu/ubicomp/extrema/workers/SyncWorker.kt#L83

**Comment by denzilferreira** [comment]
Solved in: cba5d059e6038216ec32d90ef8eecc350dd3d185
